// @flow
// Properties.js

export class AlignContent {}
export class AlignItems {}
export class AlignSelf {}
export class All {}
export class Animation {}
export class AnimationDelay {}
export class AnimationDirection {}
export class AnimationDuration {}
export class AnimationFillMode {}
export class AnimationIterationCount {}
export class AnimationName {}
export class AnimationPlayState {}
export class AnimationTimingFunction {}
export class BackfaceVisibility {}
export class Background {}
export class BackgroundAttachment {}
export class BackgroundBlendMode {}
export class BackgroundClip {}
export class BackgroundColor {}
export class BackgroundImage {}
export class BackgroundOrigin {}
export class BackgroundPosition {}
export class BackgroundRepeat {}
export class BackgroundSize {}
export class Border {}
export class BorderBottom {}
export class BorderBottomColor {}
export class BorderBottomLeftRadius {}
export class BorderBottomRightRadius {}
export class BorderBottomStyle {}
export class BorderBottomWidth {}
export class BorderCollapse {}
export class BorderColor {}
export class BorderImage {}
export class BorderImageOutset {}
export class BorderImageRepeat {}
export class BorderImageSlice {}
export class BorderImageSource {}
export class BorderImageWidth {}
export class BorderLeft {}
export class BorderLeftColor {}
export class BorderLeftStyle {}
export class BorderLeftWidth {}
export class BorderRadius {}
export class BorderRight {}
export class BorderRightColor {}
export class BorderRightStyle {}
export class BorderRightWidth {}
export class BorderSpacing {}
export class BorderStyle {}
export class BorderTop {}
export class BorderTopColor {}
export class BorderTopLeftRadius {}
export class BorderTopRightRadius {}
export class BorderTopStyle {}
export class BorderTopWidth {}
export class BorderWidth {}
export class Bottom {}
export class BoxShadow {}
export class BoxSizing {}
export class CaptionSide {}
export class Clear {}
export class Clip {}
export class Color {}
export class ColumnCount {}
export class ColumnFill {}
export class ColumnGap {}
export class ColumnRule {}
export class ColumnRuleColor {}
export class ColumnRuleStyle {}
export class ColumnRuleWidth {}
export class ColumnSpan {}
export class ColumnWidth {}
export class Columns {}
export class Content {}
export class CounterIncrement {}
export class CounterReset {}
export class Cursor {}
export class Direction {}
export class Display {}
export class EmptyCells {}
export class Filter {}
export class Flex {}
export class FlexBasis {}
export class FlexDirection {}
export class FlexFlow {}
export class FlexGrow {}
export class FlexShrink {}
export class FlexWrap {}
export class Float {}
export class Font {}
export class FontFamily {}
export class FontSize {}
export class FontSizeAdjust {}
export class FontStretch {}
export class FontStyle {}
export class FontVariant {}
export class FontWeight {}
export class HangingPunctuation {}
export class Height {}
export class JustifyContent {}
export class Left {}
export class LetterSpacing {}
export class LineHeight {}
export class ListStyle {}
export class ListStyleImage {}
export class ListStylePosition {}
export class ListStyleType {}
export class Margin {}
export class MarginBottom {}
export class MarginLeft {}
export class MarginRight {}
export class MarginTop {}
export class MaxHeight {}
export class MaxWidth {}
export class MinHeight {}
export class MinWidth {}
export class NavDown {}
export class NavIndex {}
export class NavLeft {}
export class NavRight {}
export class NavUp {}
export class Opacity {}
export class Order {}
export class Outline {}
export class OutlineColor {}
export class OutlineOffset {}
export class OutlineStyle {}
export class OutlineWidth {}
export class Overflow {}
export class OverflowX {}
export class OverflowY {}
export class Padding {}
export class PaddingBottom {}
export class PaddingLeft {}
export class PaddingRight {}
export class PaddingTop {}
export class PageBreakAfter {}
export class PageBreakBefore {}
export class PageBreakInside {}
export class Perspective {}
export class PerspectiveOrigin {}
export class Position {}
export class Quotes {}
export class Resize {}
export class Right {}
export class TabSize {}
export class TableLayout {}
export class TextAlign {}
export class TextAlignLast {}
export class TextDecoration {}
export class TextDecorationColor {}
export class TextDecorationLine {}
export class TextDecorationStyle {}
export class TextIndent {}
export class TextJustify {}
export class TextOverflow {}
export class TextShadow {}
export class TextTransform {}
export class Top {}
export class Transform {}
export class TransformOrigin {}
export class TransformStyle {}
export class Transition {}
export class TransitionDelay {}
export class TransitionDuration {}
export class TransitionProperty {}
export class TransitionTimingFunction {}
export class UnicodeBidi {}
export class VerticalAlign {}
export class Visibility {}
export class WhiteSpace {}
export class Width {}
export class WordBreak {}
export class WordSpacing {}
export class WordWrap {}
export class ZIndex {}
